export enum NewsActionEnum {
  // 创建订单
  CREATE = 'CREATE',
  // 填充资料
  MATERIAL_FILLED = 'MATERIAL_FILLED',
  // 更新资料
  MATERIAL_UPDATE = 'MATERIAL_UPDATE',
  MATERIAL_APPROVED = 'MATERIAL_APPROVED',
  MATERIAL_REJECTED = 'MATERIAL_REJECTED',
  // 订单资料全部审核通过
  REPORTING = 'REPORTING',
  // 订单已完成
  COMPLETED = 'COMPLETED',
}
