export enum OrderTypeEnum {
  // 林场|农户
  MATERIAL_PRODUCER = 'MATERIAL_PRODUCER',
  // 材料加工厂
  MATERIAL_PROCESSOR = 'MATERIAL_PROCESSOR',
  // 贸易商
  TRADER = 'TRADER',
  // 生产商
  PRODUCT_PRODUCER = 'PRODUCT_PRODUCER',
}
